export { default as heroImg } from './hero-img.png'
export { default as avatar1 } from './avatar1.png'
export { default as avatar2 } from './avatar2.png'
export { default as avatar3 } from './avatar3.png'
export { default as aboutImg } from './aboutImg.png'